#jupyter nbconvert --to=notebook --config nbconvert_config.py --output "02 - Data structures.ipynb" "solved - 02 - Data structures.ipynb" 
# jupyter nbconvert --to=notebook --output "03b - Some more advanced indexing.ipynb" "solved - 03b - Some more advanced indexing.ipynb"
#jupyter nbconvert --to=notebook --config nbconvert_config.py --output "03 - Indexing and selecting data.ipynb" "solved - 03 - Indexing and selecting data.ipynb"
#jupyter nbconvert --to=notebook --config nbconvert_config.py --output "04 - Groupby operations.ipynb" "solved - 04 - Groupby operations.ipynb"
#jupyter nbconvert --to=notebook --config nbconvert_config.py --output "04b - Advanced groupby operations.ipynb" "solved - 04b - Advanced groupby operations.ipynb"
jupyter nbconvert --to=notebook --config nbconvert_config.py --output "05 - Time series data.ipynb" "solved - 05 - Time series data.ipynb"
jupyter nbconvert --to=notebook --config nbconvert_config.py --output "06 - Reshaping data.ipynb" "solved - 06 - Reshaping data.ipynb"
jupyter nbconvert --to=notebook --config nbconvert_config.py --output "07 - Case study - air quality data.ipynb" "solved - 07 - Case study - air quality data.ipynb"
